### PR TITLE
added an option to not index arrays using an flatten_array flag

### PR DESCRIPTION
**Pull request by pavgup**
By default, the index_array option is ignored, but when it's set to false, the original array is returned attached to the key normally created.  This might be a nice option for the hashes as well.  And some mods to the readme.md file would be valuable, but how does this look?

### CODE REVIEW

**Comment by pavgup** [comment]
There we go.  Bug fixed, test added, and it looks like this is working smoothly.

**Comment by kazegusuri** [comment]
thanks, will check.

**Comment by kazegusuri** [comment]
Sorry for late reply. I don't understand the use case, but looks good to me.
If you want same feature for hash (in future), how about renaming the option name to `flat_array` or `flatten_array` ?

**Comment by pavgup** [comment]
No worries at all.  I've renamed index_array to flatten_array (good suggestion), and I've updated the readme to mention this option.  The use case is simply to make it possible to have varied length json arrays insertable directly into standard SQL tables.

**Comment by kazegusuri** [comment]
LGTM. Thanks.

**Comment by pavgup** [comment]
<3

**Pull request merged**
