### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, I've tried to migrate using v0.14 API.
Could you consider to start using v0.14 API in this plugin?

Please refer to [the upgrading v0.12 to v0.14 guide](http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12) in more details.

### CODE REVIEW

**Comment by kazegusuri** [comment]
Thank you for migrating to new API. Your changes look good.
I updated dependency to fluentd in current master, which caused conflict. After fixing the conflict, I will merge this PR.

**Comment by cosmo0920** [comment]
> I updated dependency to fluentd in current master, which caused conflict. After fixing the conflict, I will merge this PR.

Sounds great! I'll resolve this conflict in the next week.
Thanks in advance. :bow:

**Comment by cosmo0920** [comment]
I've resolved a conflict.
Could you take a look again this PR?

**Comment by kazegusuri** [comment]
Thank you . I will release a new version later.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
